package game.gfx;

import game.entity.types.Level;
import game.entity.types.Player;
import game.input.SimpleKeyboard;
import game.view.GameWindow;

import java.awt.Canvas;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferStrategy;

import javax.swing.JFrame;

public class Lerret extends Canvas{

	/**
	 * autogenerated 
	 */
	private static final long serialVersionUID = -8579638927397401101L;
	
	protected final int TILESIZE;
	protected GameWindow vindu;
	protected Level brett;
	protected Player spiller;
	protected Dimension størrelseIPiksler;
	
	public Lerret(String tittel, Level level, Player player){
		TILESIZE = level.tilesize();
		vindu = new GameWindow(tittel);
		this.størrelseIPiksler = new Dimension(level.tileColumns() * TILESIZE, level.tileRows() * TILESIZE);
		brett = level;
		spiller = player;
		
		this.setPreferredSize(størrelseIPiksler);
		this.setMinimumSize(størrelseIPiksler);
		this.setMaximumSize(størrelseIPiksler);
		this.setFocusable(true);

		vindu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		vindu.add(this);		
		vindu.pack();
		vindu.setVisible(true);
		
		this.requestFocusInWindow();
		
	}

	public void tick(){
		spiller.tick();
		brett.tick();
	}
	
	public void render(){
		BufferStrategy bs = this.getBufferStrategy();
		if(bs == null){
			createBufferStrategy(3);
			return;
		}
		Graphics g = bs.getDrawGraphics();
		
//		RENDER HERE
		g.fillRect(0, 0, størrelseIPiksler.width, størrelseIPiksler.height);
		
		if(null != brett){
			brett.render(g);
		}
		if(null != spiller){
			spiller.render(g);
		}
		
//		END RENDER
		g.dispose();
		bs.show();
		
	}
	
	public GameWindow getWindow(){
		return vindu;
	}

	public void registerKeyboard(SimpleKeyboard keyboard) {
		this.setFocusable(true);
		this.addKeyListener(keyboard);
	}
}
