package game.gfx;

import game.entity.types.Level;
import game.entity.types.Player;
import game.input.SimpleKeyboard;
import game.view.GameWindow;

import java.awt.Canvas;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferStrategy;

import javax.swing.JFrame;

public class Lerret extends Canvas{

	/**
	 * autogenerated 
	 */
	private static final long serialVersionUID = -8579638927397401101L;
	
	protected final int TILESIZE;
	protected Level brett;
	protected Player spiller;
	protected Dimension størrelseIPiksler;
	protected PaintingThread painter;
	
	public Lerret(Level level, Player player, SimpleKeyboard keyboard){		
		TILESIZE = level.tilesize();
		this.størrelseIPiksler = new Dimension(level.tileColumns() * TILESIZE, level.tileRows() * TILESIZE);
		brett = level;
		spiller = player;
		
		this.setPreferredSize(størrelseIPiksler);
		this.setMinimumSize(størrelseIPiksler);
		this.setMaximumSize(størrelseIPiksler);
		this.setFocusable(true);
		
		this.registerKeyboard(keyboard);
		this.requestFocusInWindow();
		painter = new PaintingThread(this);
		
	}
	
	public void setLevel(Level level){
		this.brett = level;
	}
	
	public void tick(){
		spiller.tick();
		brett.tick();
	}
	
	public void render(){
		BufferStrategy bs = this.getBufferStrategy();
		if(bs == null){
			createBufferStrategy(3);
			return;
		}
		Graphics g = bs.getDrawGraphics();
		
//		RENDER HERE
		g.fillRect(0, 0, størrelseIPiksler.width, størrelseIPiksler.height);
		
		if(null != brett){
			brett.render(g);
		}
		if(null != spiller){
			spiller.render(g);
		}
		
//		END RENDER
		g.dispose();
		bs.show();
		
	}
	
	public void registerKeyboard(SimpleKeyboard keyboard) {
		this.setFocusable(true);
		this.addKeyListener(keyboard);
	}
}
